spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://19.224.172.191:14330;database=app_router;
    username: sa
    password: dev@123,
  jpa:
    show-sql: true
    open-in-view: false




