camel:
  springboot:
    name: MyCamel
    main-run-controller: true
    routesIncludePattern: "classpath:camel/*,classpath:camel-template/*,classpath:camel-rest/*"
  component:
    # ServletComponentConfiguration
    servlet:
      enabled: true
      # ServletMappingConfiguration
      mapping:
        # 只有禁用掉系统默认的ServletMappingAutoConfiguration, 才能启用我们自定义的ServletMappingAutoConfiguration
        enabled: false

  servlet:
    mapping:
      context-path: /app-router/*

management:
  endpoints:
    web:
      exposure:
        include: hawtio,jolokia

hawtio:
  authenticationEnabled: false

greeting: hellofoo
timer:
  period: 10000

header:
    CamelTimerCounter: test11

routerDefinition:

#log4j:
#  logger:
#    org:
#      apache:
#        camel: DEBUG
